<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-07-30 15:13
=======
# Generated by Django 2.0.3 on 2018-07-30 15:11
>>>>>>> b6ab87fb2b896307c77586a7c07a3710b6c7a4ef

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('textid', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
