import React, {Component} from 'react';

export const Sep_e = [
    {
        'text': '店',
        'value': 12.0
    }, {
        'text': '駕駛',
        'value': 12.0
    }, {
        'text': '餐廳',
        'value': 12.0
    }, {
        'text': '分局',
        'value': 9.0
    }, {
        'text': '店家',
        'value': 9.0
    }, {
        'text': '劉強',
        'value': 9.0
    }, {
        'text': '東',
        'value': 9.0
    }, {
        'text': '口味',
        'value': 9.0
    }, {
        'text': '山竹',
        'value': 9.0
    }, {
        'text': '起訴',
        'value': 9.0
    }, {
        'text': '大阪',
        'value': 21.0
    }, {
        'text': '接殺',
        'value': 18.0
    }, {
        'text': '失分',
        'value': 18.0
    }, {
        'text': '滾地球',
        'value': 18.0
    }, {
        'text': '球隊',
        'value': 18.0
    }, {
        'text': '安打',
        'value': 18.0
    }, {
        'text': '本季',
        'value': 15.0
    }, {
        'text': '局下',
        'value': 15.0
    }, {
        'text': '外野',
        'value': 15.0
    }, {
        'text': '刺殺',
        'value': 15.0
    }, {
        'text': '縣長',
        'value': 6.0
    }, {
        'text': '參選人',
        'value': 6.0
    }, {
        'text': '侯友宜',
        'value': 6.0
    }, {
        'text': '改善',
        'value': 6.0
    }, {
        'text': '科技',
        'value': 6.0
    }, {
        'text': '報告',
        'value': 6.0
    }, {
        'text': '會議',
        'value': 6.0
    }, {
        'text': '非洲',
        'value': 6.0
    }, {
        'text': '市民',
        'value': 6.0
    }, {
        'text': '建設',
        'value': 6.0
    }, {
        'text': '導演',
        'value': 9.0
    }, {
        'text': '結婚',
        'value': 9.0
    }, {
        'text': '吳音寧',
        'value': 9.0
    }, {
        'text': '觀眾',
        'value': 9.0
    }, {
        'text': '故事',
        'value': 9.0
    }, {
        'text': '飾演',
        'value': 9.0
    }, {
        'text': '人生',
        'value': 9.0
    }, {
        'text': '演員',
        'value': 9.0
    }, {
        'text': '音樂',
        'value': 9.0
    }, {
        'text': '舞台',
        'value': 6.0
    }, {
        'text': '寵物',
        'value': 15.0
    }, {
        'text': '家屬',
        'value': 12.0
    }, {
        'text': '檢查',
        'value': 12.0
    }, {
        'text': '疑似',
        'value': 12.0
    }, {
        'text': '狗狗',
        'value': 12.0
    }, {
        'text': '醫生',
        'value': 9.0
    }, {
        'text': '救援',
        'value': 9.0
    }, {
        'text': '喵',
        'value': 9.0
    }, {
        'text': '貓咪',
        'value': 9.0
    }, {
        'text': '緊急',
        'value': 9.0
    }

]

export const Sep_l = [
    {
        'text': '姓',
        'value': 9.0
    }, {
        'text': '員警',
        'value': 9.0
    }, {
        'text': '機車',
        'value': 9.0
    }, {
        'text': '毒品',
        'value': 9.0
    }, {
        'text': '事後',
        'value': 9.0
    }, {
        'text': '發文',
        'value': 9.0
    }, {
        'text': '母親',
        'value': 9.0
    }, {
        'text': '狗',
        'value': 9.0
    }, {
        'text': '回家',
        'value': 9.0
    }, {
        'text': '派出所',
        'value': 6.0
    }, {
        'text': '公開賽',
        'value': 15.0
    }, {
        'text': '競選',
        'value': 15.0
    }, {
        'text': '轉會',
        'value': 15.0
    }, {
        'text': '周天',
        'value': 15.0
    }, {
        'text': '瑜',
        'value': 15.0
    }, {
        'text': '縣長',
        'value': 15.0
    }, {
        'text': '盃',
        'value': 12.0
    }, {
        'text': '立委',
        'value': 12.0
    }, {
        'text': '賽事',
        'value': 12.0
    }, {
        'text': '高中',
        'value': 12.0
    }, {
        'text': '業務員',
        'value': 9.0
    }, {
        'text': '創新',
        'value': 9.0
    }, {
        'text': '降低',
        'value': 9.0
    }, {
        'text': '風險',
        'value': 6.0
    }, {
        'text': '銷售',
        'value': 6.0
    }, {
        'text': '藥物',
        'value': 6.0
    }, {
        'text': '智慧',
        'value': 6.0
    }, {
        'text': '改善',
        'value': 6.0
    }, {
        'text': '保單',
        'value': 6.0
    }, {
        'text': '患者',
        'value': 6.0
    }, {
        'text': '桃猿',
        'value': 27.0
    }, {
        'text': '保送',
        'value': 24.0
    }, {
        'text': '中信',
        'value': 24.0
    }, {
        'text': '防禦率',
        'value': 24.0
    }, {
        'text': '北韓',
        'value': 24.0
    }, {
        'text': '接殺',
        'value': 24.0
    }, {
        'text': '局下',
        'value': 24.0
    }, {
        'text': '安打',
        'value': 21.0
    }, {
        'text': '悍將',
        'value': 21.0
    }, {
        'text': '局上',
        'value': 21.0
    }, {
        'text': '川普',
        'value': 15.0
    }, {
        'text': '咖啡',
        'value': 12.0
    }, {
        'text': '出境',
        'value': 12.0
    }, {
        'text': '居住證',
        'value': 12.0
    }, {
        'text': '料理',
        'value': 12.0
    }, {
        'text': '餐廳',
        'value': 12.0
    }, {
        'text': '關稅',
        'value': 9.0
    }, {
        'text': '貿易',
        'value': 9.0
    }, {
        'text': '億美元',
        'value': 9.0
    }, {
        'text': '台商',
        'value': 9.0
    }, {
        'text': '飾演',
        'value': 9.0
    }, {
        'text': '作品',
        'value': 9.0
    }, {
        'text': '拆除',
        'value': 6.0
    }, {
        'text': '音樂',
        'value': 6.0
    }, {
        'text': '觀眾',
        'value': 6.0
    }, {
        'text': '風格',
        'value': 6.0
    }, {
        'text': '表演',
        'value': 6.0
    }, {
        'text': '致',
        'value': 6.0
    }, {
        'text': '充滿',
        'value': 6.0
    }, {
        'text': '創意',
        'value': 6.0
    }
]

export const Oct_e = [
    {
        'text': '競選',
        'value': 15.0
    }, {
        'text': '川普',
        'value': 15.0
    }, {
        'text': '深澳',
        'value': 15.0
    }, {
        'text': '賴清德',
        'value': 15.0
    }, {
        'text': '人民',
        'value': 12.0
    }, {
        'text': '發言人',
        'value': 12.0
    }, {
        'text': '會議',
        'value': 12.0
    }, {
        'text': '議題',
        'value': 12.0
    }, {
        'text': '公投',
        'value': 12.0
    }, {
        'text': '縣長',
        'value': 12.0
    }, {
        'text': '遊客',
        'value': 12.0
    }, {
        'text': '商品',
        'value': 12.0
    }, {
        'text': '餐廳',
        'value': 12.0
    }, {
        'text': '消費',
        'value': 9.0
    }, {
        'text': '購買',
        'value': 9.0
    }, {
        'text': '打造',
        'value': 9.0
    }, {
        'text': '平台',
        'value': 9.0
    }, {
        'text': '智慧',
        'value': 9.0
    }, {
        'text': '料理',
        'value': 9.0
    }, {
        'text': '出口',
        'value': 9.0
    }, {
        'text': '撞',
        'value': 15.0
    }, {
        'text': '姓',
        'value': 15.0
    }, {
        'text': '毒品',
        'value': 12.0
    }, {
        'text': '家屬',
        'value': 12.0
    }, {
        'text': '派出所',
        'value': 12.0
    }, {
        'text': '立即',
        'value': 12.0
    }, {
        'text': '車禍',
        'value': 12.0
    }, {
        'text': '到場',
        'value': 12.0
    }, {
        'text': '偵辦',
        'value': 12.0
    }, {
        'text': '檢舉',
        'value': 9.0
    }, {
        'text': '出局',
        'value': 24.0
    }, {
        'text': '三振',
        'value': 24.0
    }, {
        'text': '生涯',
        'value': 24.0
    }, {
        'text': '桃猿',
        'value': 24.0
    }, {
        'text': '富邦',
        'value': 24.0
    }, {
        'text': '軍',
        'value': 21.0
    }, {
        'text': '二壘',
        'value': 21.0
    }, {
        'text': '防禦率',
        'value': 21.0
    }, {
        'text': '主場',
        'value': 21.0
    }, {
        'text': '道奇',
        'value': 21.0
    }, {
        'text': '愛',
        'value': 9.0
    }, {
        'text': '寵物',
        'value': 6.0
    }, {
        'text': '幫',
        'value': 6.0
    }, {
        'text': '老公',
        'value': 6.0
    }, {
        'text': '父母',
        'value': 6.0
    }, {
        'text': '財運',
        'value': 6.0
    }, {
        'text': '結婚',
        'value': 6.0
    }, {
        'text': '玩',
        'value': 6.0
    }, {
        'text': '狗狗',
        'value': 6.0
    }, {
        'text': '醫療',
        'value': 15.0
    }, {
        'text': '器官',
        'value': 15.0
    }, {
        'text': '患者',
        'value': 15.0
    }, {
        'text': '教育',
        'value': 15.0
    }, {
        'text': '入圍',
        'value': 15.0
    }, {
        'text': '病人',
        'value': 12.0
    }, {
        'text': '家長',
        'value': 12.0
    }, {
        'text': '典禮',
        'value': 9.0
    }, {
        'text': '億',
        'value': 9.0
    }, {
        'text': '得獎',
        'value': 9.0
    }, {
        'text': '指數',
        'value': 21.0
    }, {
        'text': '音樂',
        'value': 18.0
    }, {
        'text': '中華',
        'value': 15.0
    }, {
        'text': '舞台',
        'value': 15.0
    }, {
        'text': '作品',
        'value': 15.0
    }, {
        'text': '玩家',
        'value': 15.0
    }, {
        'text': '成員',
        'value': 12.0
    }, {
        'text': '演唱會',
        'value': 12.0
    }, {
        'text': '高中',
        'value': 12.0
    }, {
        'text': '台股',
        'value': 12.0
    }

]

export const Oct_l = [
    {
        'text': '邱議瑩',
        'value': 18.0
    }, {
        'text': '段',
        'value': 12.0
    }, {
        'text': '彰化',
        'value': 12.0
    }, {
        'text': '選民',
        'value': 9.0
    }, {
        'text': '睡',
        'value': 9.0
    }, {
        'text': '選戰',
        'value': 9.0
    }, {
        'text': '地震',
        'value': 9.0
    }, {
        'text': '政見',
        'value': 9.0
    }, {
        'text': '同志',
        'value': 9.0
    }, {
        'text': '抹黑',
        'value': 9.0
    }, {
        'text': '好友',
        'value': 9.0
    }, {
        'text': '老公',
        'value': 9.0
    }, {
        'text': '人生',
        'value': 9.0
    }, {
        'text': '沙國',
        'value': 6.0
    }, {
        'text': '戴',
        'value': 6.0
    }, {
        'text': '不想',
        'value': 6.0
    }, {
        'text': '演員',
        'value': 6.0
    }, {
        'text': '直呼',
        'value': 6.0
    }, {
        'text': 'LINE',
        'value': 6.0
    }, {
        'text': '播出',
        'value': 6.0
    }, {
        'text': '台股',
        'value': 9.0
    }, {
        'text': '交通部',
        'value': 9.0
    }, {
        'text': '作業',
        'value': 9.0
    }, {
        'text': '測試',
        'value': 9.0
    }, {
        'text': '補助',
        'value': 9.0
    }, {
        'text': '外資',
        'value': 9.0
    }, {
        'text': '高鐵',
        'value': 9.0
    }, {
        'text': '死者',
        'value': 27.0
    }, {
        'text': '樓',
        'value': 12.0
    }, {
        'text': '時分',
        'value': 12.0
    }, {
        'text': '大樓',
        'value': 12.0
    }, {
        'text': '同學',
        'value': 12.0
    }, {
        'text': '初步',
        'value': 12.0
    }, {
        'text': '分局',
        'value': 12.0
    }, {
        'text': '偵辦',
        'value': 12.0
    }, {
        'text': '釐清',
        'value': 9.0
    }, {
        'text': '起訴',
        'value': 9.0
    }, {
        'text': '球',
        'value': 18.0
    }, {
        'text': '出局',
        'value': 18.0
    }, {
        'text': '失分',
        'value': 18.0
    }, {
        'text': '首局',
        'value': 18.0
    }, {
        'text': '陽春',
        'value': 18.0
    }, {
        'text': '生涯',
        'value': 18.0
    }, {
        'text': '局上',
        'value': 18.0
    }, {
        'text': '球場',
        'value': 18.0
    }, {
        'text': '總教練',
        'value': 15.0
    }, {
        'text': '保送',
        'value': 15.0
    }, {
        'text': '萬聖節',
        'value': 18.0
    }, {
        'text': '酒店',
        'value': 15.0
    }, {
        'text': '造型',
        'value': 12.0
    }, {
        'text': '公車',
        'value': 12.0
    }, {
        'text': '堅果',
        'value': 12.0
    }, {
        'text': '效果',
        'value': 12.0
    }, {
        'text': '澳洲',
        'value': 9.0
    }, {
        'text': '飛機',
        'value': 9.0
    }, {
        'text': '口感',
        'value': 9.0
    }, {
        'text': '航空',
        'value': 9.0
    }
]

export const Nov_e = [
    {
        'text': '玩家',
        'value': 12.0
    }, {
        'text': '原價',
        'value': 12.0
    }, {
        'text': '遊戲',
        'value': 9.0
    }, {
        'text': '料理',
        'value': 9.0
    }, {
        'text': '購物',
        'value': 9.0
    }, {
        'text': '限量',
        'value': 9.0
    }, {
        'text': '餐廳',
        'value': 9.0
    }, {
        'text': '風格',
        'value': 9.0
    }, {
        'text': '免費',
        'value': 9.0
    }, {
        'text': '擊出',
        'value': 24.0
    }, {
        'text': '三振',
        'value': 21.0
    }, {
        'text': '籃板',
        'value': 21.0
    }, {
        'text': '本季',
        'value': 18.0
    }, {
        'text': '賽事',
        'value': 18.0
    }, {
        'text': '進攻',
        'value': 18.0
    }, {
        'text': '隊',
        'value': 18.0
    }, {
        'text': '助攻',
        'value': 18.0
    }, {
        'text': '總教練',
        'value': 18.0
    }, {
        'text': '先發',
        'value': 18.0
    }, {
        'text': '醫師',
        'value': 15.0
    }, {
        'text': '東森',
        'value': 15.0
    }, {
        'text': '患者',
        'value': 15.0
    }, {
        'text': '食物',
        'value': 12.0
    }, {
        'text': '作品',
        'value': 12.0
    }, {
        'text': '治療',
        'value': 12.0
    }, {
        'text': '皮膚',
        'value': 12.0
    }, {
        'text': '假釋',
        'value': 12.0
    }, {
        'text': '音樂',
        'value': 12.0
    }, {
        'text': '動物',
        'value': 9.0
    }, {
        'text': '員警',
        'value': 12.0
    }, {
        'text': '兒子',
        'value': 12.0
    }, {
        'text': '爸爸',
        'value': 12.0
    }, {
        'text': '女子',
        'value': 9.0
    }, {
        'text': '事後',
        'value': 9.0
    }, {
        'text': '狗狗',
        'value': 9.0
    }, {
        'text': '分局',
        'value': 9.0
    }, {
        'text': '老公',
        'value': 9.0
    }, {
        'text': '司機',
        'value': 9.0
    }, {
        'text': '疑似',
        'value': 9.0
    }, {
        'text': '共和黨',
        'value': 9.0
    }, {
        'text': '億美元',
        'value': 9.0
    }, {
        'text': '人民幣',
        'value': 9.0
    }, {
        'text': '董事長',
        'value': 9.0
    }, {
        'text': '期中',
        'value': 9.0
    }, {
        'text': '委員會',
        'value': 9.0
    }, {
        'text': '增長',
        'value': 9.0
    }, {
        'text': '國內',
        'value': 9.0
    }, {
        'text': '報告',
        'value': 9.0
    }, {
        'text': '貿易',
        'value': 6.0
    }, {
        'text': '小野',
        'value': 12.0
    }, {
        'text': '辯論',
        'value': 9.0
    }, {
        'text': '愛情',
        'value': 9.0
    }, {
        'text': '選情',
        'value': 9.0
    }, {
        'text': '記者會',
        'value': 9.0
    }, {
        'text': '高雄市',
        'value': 9.0
    }, {
        'text': '台鐵',
        'value': 9.0
    }, {
        'text': '兩岸',
        'value': 9.0
    }, {
        'text': '財運',
        'value': 9.0
    }, {
        'text': '侯友宜',
        'value': 9.0
    }

]

export default Sep_e;
